language: objective-c
osx_image: xcode10.2
cache: cocoapods
before_install:
  - pod repo update
after_success:
  - ls
  - bash <(curl -s https://codecov.io/bash) -J 'AerialApp'
before_script:
  - make lint
script:
  - make test-travis
